---
version: "3.5"
services:
  etcd:
    image: 'bitnami/etcd:latest'
    container_name: hb-etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2400:2379
      - 2500:2380
