stages:
  - test

.auto_devops: &auto_devops |
  # Auto DevOps variables and functions
  [[ "$TRACE" ]] && set -x

  function install() {
    # 删除k8s部署
    helm uninstall hbgin ./chart --namespace gin
    # 添加k8s部署
    helm uninstall hbgin ./chart --namespace gin --create-namespace
  }

before_script:
  - *auto_devops

master_job:
  stage: test
  only:
    refs:
      - master
  script:
    - install
  when: manual