version: "3"

services:
  postgres:
    image: postgres
    container_name: local_postgresql
    restart: always
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432