version: '2.2'
services:
  kafka-zookeeper:
    image: wurstmeister/zookeeper
    container_name: kafka-zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - "kafka_net"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    hostname: kafka-hostname
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_MAX_REQUEST_SIZE: 5242880
      KAFKA_HEAP_OPTS: -Xms2G -Xmx2G
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - "kafka_net"
  kafka-manage:
    image: sheepkiller/kafka-manager
    container_name: kafka-manage
    restart: always
    ports:
      - "5001:9000"
    environment:
      ZK_HOSTS: kafka-zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
    networks:
      - "kafka_net"
networks:
  kafka_net:
    external: true
